[package]
name = "drift-store"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bincode.workspace = true
chrono.workspace = true
drift-domain = { path = "../drift-domain" }
rusqlite.workspace = true
thiserror.workspace = true
zstd.workspace = true
